### ISSUE TITLE
Input onBlur problem

### ISSUE THREAD

**Issue by uragecz** [Norserium/react-indiana-drag-scroll#33] opened 2020-05-06 20:15 UTC
Hey, i have problem, when there is input inside ScrollContainer.... and i am clicking inside this container (outside the input)... input event onBlur isn't called... Any workaround for this ? Or incoming fix? Thanks !

**Comment by Norserium** [comment] 2020-05-06 20:24
Hello, @uragecz! I suppose, that your problem is described in the another issue. My response is [here](https://github.com/Norserium/react-indiana-drag-scroll/issues/31#issuecomment-610309591).

**Comment by Norserium** [comment] 2020-05-06 20:28
Hello, @uragecz! Could you provide the sandbox that reproduces the described problem? I [can't reproduce](https://codesandbox.io/s/react-indiana-drag-scroll-default-swxue?file=/index.js:0-587) it.

**Comment by uragecz** [comment] 2020-05-06 20:55
@Norserium  I am trying to reproduce it on sandbox.. howerver for now without success.. howerver in my code i tried to put everything away.. just to keep there input.. and same problem.. also wondering.. how you are able to click on it when input isn't in ignore list ?

**Comment by uragecz** [comment] 2020-05-06 20:57
I have just this right now - https://ibb.co/7RCSG2g

**Comment by Norserium** [comment] 2020-05-06 20:59
I've set wrong version in that example. Now I reproduced this problem successfully.

**Comment by uragecz** [comment] 2020-05-06 21:01
Ah, so workaround is to set older version.. can you tell me which one you had there.. ?

**Comment by Norserium** [comment] 2020-05-06 21:06
No, it's not. Me need some time to investigate the real solution, because it's pretty tough situation. I should prevent default behavior on click at the draggable element, but when I prevent default behavior I prevent blur event also.

**Comment by Norserium** [comment] 2020-05-06 21:10
Perhaps, it's needed `preventDefault` prop, that can be used to disable preventing default behavior for click/touches. But it's pretty straightforward solution.

**Comment by uragecz** [comment] 2020-05-06 21:18
But for now it can work

**Comment by Norserium** [comment] 2020-05-06 21:59
There are plenty of different bugs, that were eliminated at the next versions. For example, you can user the following [temporary solution](https://codesandbox.io/s/react-indiana-drag-scroll-default-rdk1q?file=/index.js).

**Comment by ZempaiZemex** [comment] 2020-05-25 13:30
any progress ?

**Comment by Norserium** [comment] 2020-05-25 13:51
@ZempaiZemex, I didn't decided what solution I should implement. It seems that there is no the universal solution that would be suitable for all cases.

Currently you could use the [temporary solution](https://codesandbox.io/s/react-indiana-drag-scroll-default-rdk1q?file=/index.js) mentioned above.

**Comment by uragecz** [comment] 2020-05-26 09:11
@Norserium  This temporary solution is pretty bad... if input is inside some component somewhere deep.. you need to pass REF many times.. and this is unacceptable solution.. In other words this libarary for this case is unusable ..

**Comment by Norserium** [comment] 2020-05-26 09:49
@uragecz, why do you should pass ref many times? Could you show this case? The ref used in my example is not passed to any elements. I [changed the example](https://codesandbox.io/s/react-indiana-drag-scroll-deep-bs5go?file=/index.js) to use the nested component with input element.

**Comment by uragecz** [comment] 2020-05-26 12:19
@Norserium  Sorry, my fault... i thought that your input ref is ref of those inputs inside scroll container.. but it's just ref of "nothing"... Soo it finally works. Ty for this workaround, you can close it if you want.

**Comment by Norserium** [comment] 2020-05-26 12:25
@uragecz, this ref is exist only to contain the internal state. I can use `useState` hook but it will produce the redundant rerender. To make this workaround more beautiful you may wrap it in [a hook](https://codesandbox.io/s/react-indiana-drag-scroll-usescrollcontainerclick-exrzp?file=/index.js).

But I'm not going to close this issue in the near future. Problem is exist and there is only workaround to solve it.

**Comment by Norserium** [comment] 2022-09-26 15:42
@uragecz, this issue is resolved in [`3.x.x` (currently in the alpha test)](https://norserium.github.io/react-indiana-drag-scroll/). But you steel may be need to add `"input"` to `ignoreElements` to prevent the selection issues ([example](https://norserium.github.io/react-indiana-drag-scroll/docs/recipes#inputs)).

**Closed by Norserium** 2022-09-26 15:42 UTC
