### ISSUE TITLE
cant click input area

### ISSUE THREAD

**Issue by messcall** [Norserium/react-indiana-drag-scroll#31] opened 2020-04-06 22:09 UTC
<ScrollContainer className="container" nativeMobileScroll={true} onClick={(...args) => { console.log('onClick', args) }}>
                        <div className="col-lg-8">

                            <Form>

                                <Row>

                                    <Col>
                                        <FormGroup>
                                            <Label for="exampleEmail">Role Adı</Label>

                                            <Input
                                                type="text"
                                                name="roleName"
                                                id="roleName"
                                                placeholder="Role Adı Belirleyiniz!"
                                                value={this.state.roleName}
                                                onChange={this.setOnChange}
                                            />

                                        </FormGroup>
                                    </Col>

                                </Row>

                                <Button block size="lg" onClick={this.onSubmit}  >Rolü Oluştur</Button>
                            </Form>

                        </div>
                    </ScrollContainer>

input cant click and focus so cant typing text

**Comment by Norserium** [comment] 2020-04-06 22:17
Hello, @messcall! What the version of package do you use?

**Comment by messcall** [comment] 2020-04-07 08:22
react-indiana-drag-scroll@1.6.1

**Comment by Norserium** [comment] 2020-04-07 09:17
Could you provide sandbox that reproduces your problem? I can't reproduce it ([my sandbox](https://codesandbox.io/s/react-indiana-drag-scroll-default-vu7jr?file=/index.js)).

**Comment by messcall** [comment] 2020-04-07 09:33
ı use ScrollContainer like at your sandbox code,
ı think that some css codes ı have wrote, reasons this problem.if ı solve,ı will notify here.

**Comment by Norserium** [comment] 2020-04-07 09:38
I've reproduced this bug (in sandbox above I've used the wrong version). I will investigate the solution.

**Comment by messcall** [comment] 2020-04-07 09:41
thanks for ur help u have shown

**Comment by Norserium** [comment] 2020-04-07 10:32
I've reproduced it. Alas, it's a pretty tough situation. 

When you, for example, click on the element I don't know will you scroll container or not, it depends at your further interaction. I should prevent default behavior (i.e. click), because scrolling should not be messed with clicks and other interactions. 

Me need to investigate how to solve this problem. I see two solutions pretty beautiful solutions now:
1. Add `input` tag to `ignoreElements` prop. It will disable scrolling for elements with tag `input` (feel free to set any selector here).
2. Add custom handler in `onClick` prop:
```js
handler(event) {
   if (event.target.focus) {
       event.target.focus();
   } else {
       event.target.click();
   }
}
```

**Comment by messcall** [comment] 2020-04-07 10:53
<ScrollContainer className="scroll-container" nativeMobileScroll={true} ignoreElements={Input}> .... => ... ignoreElements={Input} .... => solved problem...

**Comment by Norserium** [comment] 2020-09-25 17:53
I close this issue now. Maybe in the future I will return to this issue, but I don't want to make this library more complicated right now.

**Closed by Norserium** 2020-09-25 17:53 UTC
